### ISSUE TITLE
Variable Frequency Option

### ISSUE THREAD

**Issue by mishras1132** [gavinlyonsrepo/pic_12F675_projects#1]
Sir in LED PWM pot code can we have an option to change the frequency as well. As of now in that code we can very the dutycycle with pot using ADC of uC but my requirement is same but on different frequency. Can you please guide?

**Comment by gavinlyonsrepo** [comment]
Hi

This PIC does not have any CCP modules, so it can't do PWM in hardware.
You can do it in software, if you're not doing anything else.  
I would use a  different PIC than  PIC12F675.

You can change PWM frequency by changing the CPU frequency of PIC12F675 microcontroller. 
Also, you can change PWM frequency by changing the frequency Pre-Scalar of timer0 in the code.
To calculator output frequency you can use PIC timer calculator.

Regards
